version: "3"

services:
 
   Nginx1:
    container_name: Nginx1
    restart: always
    image: nginx:latest
    networks:
      - net1
    ports:
      - "8001:80"
    volumes:
      - ./config1/:/etc/nginx/conf.d/
  
  Nginx2:
    container_name: Nginx2
    restart: always
    image: nginx:latest
    networks:
      - net1
    ports:
      - "8002:80"
    volumes:
      - ./config2/:/etc/nginx/conf.d/   
 
  Grafana:
    container_name: Grafana
    restart: unless-stopped
    image: Grafana
    networks:
      - net1
      - net2
    ports:
      - "8002:80"
    expose:
      - 3000



networks:
  net1:
  net2:


  
