version: "3"

services:
 
   nginx1:
    container_name: nginx1
    restart: always
    image: nginx:latest
    networks:
      - net1
    ports:
      - "8001:80"
    volumes:
      - ./config1/:/etc/nginx/conf.d/
  
  nginx2:
    container_name: nginx2
    restart: always
    image: nginx:latest
    networks:
      - net1
    ports:
      - "8002:80"
    volumes:
      - ./config2/:/etc/nginx/conf.d/   
 
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: Grafana
    networks:
      - net1
      - net2
    expose:
      - 3000



networks:
  net1:
  net2:


  
